spring:
  application:
    name: tripgg

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: update
    defer-datasource-initialization: true # hibernate 초기화 이후 data.sql 실행
    show-sql: true
    properties:
      hibernate:
        format_sql: true;
        use_sql_comments: true


  profiles:
    active: local
    include: secret

  sql:
    init:
      mode: never  # 모든 데이터베이스로 초기화 대상 변경

logging:
  level:
    org.hibernate.SQL: debug          # SQL 쿼리 출력
    org.hibernate.type.descriptor.sql: trace  # 쿼리 파라미터 출력
    # 또는
    org.hibernate.orm.jdbc.bind: trace  # 쿼리 파라미터 출력 (최신 버전)
    org.hibernate.engine.QueryParameters: trace
    org.hibernate.engine.query.spi.HQLQueryPlan: trace